### ISSUE TITLE
关于运行python init.py -port=8888的一个错误

### ISSUE THREAD

**Issue by mqwHub** [ireaderlab/zkdash#1]
File "/usr/lib/python2.7/site-packages/kazoo/hosts.py", line 3, in <module>
    from six.moves import urllib_parse
ImportError: cannot import name urllib_parse

**Comment by paderma** [comment]
有可能是six包的版本过低导致的，你运行`pip freeze | grep six`命令，看一下six的版本号
我使用的是six的1.10.0版本
