### ISSUE TITLE
数据库断开连接后重连失败

### ISSUE THREAD

**Issue by niubell** [ireaderlab/zkdash#2]
错误日志:
error.log
[WARNING 2015-10-19 10:04:48,530 base.py 133] Mysql OperationalError: (2006, 'MySQL server has gone away')
zkdash.log
[INFO 2015-10-19 10:04:48,515 base.py 25] 重连数据库...
[INFO 2015-10-19 10:04:48,516 init.py 65] 302 GET /config/snapshot/index?target_tab=_config_snapshot&_xsrf=2%7C17bfb130%7Cdc3a69e4a29362a6b33165d284f8b5b3%7C1444999331&_=1445220289410 (36.110.17.2) 2.02ms
[DEBUG 2015-10-19 10:04:48,529 peewee.py 2865]('SELECT Count%28*%29 FROM `zd_zookeeper` AS t1 WHERE %28`t1`.`deleted` = %s%29', ['0'])
[WARNING 2015-10-19 10:04:48,530 base.py 133] Mysql OperationalError: (2006, 'MySQL server has gone away')

**Comment by paderma** [comment]
mysql重连bug已经修复，请下载最新版本的zkdash
