### ISSUE TITLE
添加agent不能选择zk集群

### ISSUE THREAD

**Issue by niubell** [ireaderlab/zkdash#3]
![z3_jc5d8u_4nwx 7bfns49e](https://cloud.githubusercontent.com/assets/8213772/10568639/7e01cfce-764d-11e5-83d3-d4c6d219d477.jpg)

集群情况: 配置了一个集群
操作系统: MacOS
浏览器    : Chrome

**Comment by paderma** [comment]
新提交的代码修复了这个bug

**Comment by xidianwlc** [comment]
问题已经解决，请拉取最新代码即可。
