### ISSUE TITLE
点击“批量增改”弹出窗口，当键值为Json格式时无法正常显示，显示为[object Object]

### ISSUE THREAD

**Issue by lzjohnny** [ireaderlab/zkdash#31]
![screenshot](https://user-images.githubusercontent.com/12896695/51082618-ab8f7a80-1745-11e9-9225-7d212dca5cad.JPG)

**Comment by lzjohnny** [comment]
已解决，见：https://github.com/ireaderlab/zkdash/pull/30/commits/c37ea8dff3894550a37d3c18a648e51ab0257c3d

**Comment by xidianwlc** [comment]
我会抽时间merge，感谢
