### ISSUE TITLE
根据文档修改配置文件中的 Use_conf 无法获取子节点

### ISSUE THREAD

**Issue by bddiudiu** [ireaderlab/zkdash#5]
修改了配置文件中的use_conf=True
重启zkdash 点击配置管理 后台显示  node does not exists on Qconf agent:
agent 手动 get了一下 还是有如上错误 
请问哪里配置不对?

另: 配置完zookeeper后 agent是否只能手动配置?

**Comment by xidianwlc** [comment]
qconf 的agent还是需要启动的，启动的时候指定zookeeper的配置信息即可

**Comment by bddiudiu** [comment]
意思是 新搭建好了 zkdash 配置好 zookeeper 后 在启动 qconf的agent 然后 zkdash会自己获取我的agent?

然后 可否解答一下 第一个那个后台显示 node does not exists on Qconf agent 的问题?

**Comment by paderma** [comment]
后台显示node does not exists on Qconf agent 的问题是因为通过qconf的agent去获取数据时出错了
有可能是你本地的agent没启动或则有错误
