### ISSUE TITLE
树形展示配置信息优化

### ISSUE THREAD

**Issue by lsave** [ireaderlab/zkdash#7]
现在如果直接从根查起，貌似是一次性遍历所有节点出来的？
如果改成逐级展示，打开某个父节点的时候再去取子节点的信息会不会更能应对配置较多的场景？

**Comment by paderma** [comment]
对查询节点进行全量展示主要是考虑到方便直接进行节点操作
ps: 如果因为节点太多导致响应时间过长，可以改为通过QConf获取数据
